Update liquidity.proto
tendermint/liquidity pull request #374
Opened 2021-05-28 20:16 UTC by barriebyron

making suggested edits here in this smaller, easier-to-process PR than in https://github.com/tendermint/liquidity/pull/235

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-05-29 10:50 UTC, hallazzang commented
Thank you @barriebyron.
The generation of the corresponding `*.pb.go` files is needed too, would you mind if I do it for you and push to your branch?

2021-05-31 06:52 UTC, kogisin requested changes
@hallazzang makes a good point that the generation of the corresponding *.pb.go files is needed when there is a change in any of the `.proto` files. Since this requires development environment in your computer, we will handle this.

2021-05-31 06:55 UTC, kogisin reviewed
On top of what @hallazzang says, it seems like test coverage fails. Let me pull this branch and test out.

2021-05-31 09:22 UTC, kogisin approved these changes

2021-06-02 07:21 UTC, dongsam approved these changes

2021-06-02 07:22 UTC, merged