Add query a pool endpoint through poolCoin or reserveAcc
tendermint/liquidity pull request #390
Opened 2021-06-03 05:24 UTC by dongsam

## Description

closes: #345

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-06-04 06:47 UTC, hallazzang requested changes

2021-06-04 06:47 UTC, hallazzang commented on proto/tendermint/liquidity/v1beta1/query.proto
> +        option (google.api.http).get = "/tendermint/liquidity/v1beta1/pools/{pool_coin_denom}";
Wouldn't it conflict with current endpoint for querying pool by pool id?
https://github.com/tendermint/liquidity/blob/cdc771781e4e02f9ad03d3691f3b465847f8c700/proto/tendermint/liquidity/v1beta1/query.proto#L38

2021-06-04 06:47 UTC, hallazzang commented on x/liquidity/keeper/grpc_query.go
> +	if req == nil || req == empty {
Please check https://github.com/tendermint/liquidity/pull/391 for possible fix

2021-06-09 03:05 UTC, kogisin reviewed
In terms of functionality, I tested both CLI and REST interfaces and they work well. Everything looks good to me other than the two dots used in `query.proto` file and the TODO comment you left in `utils.go`

2021-06-09 07:40 UTC, merged